### ISSUE TITLE
GetProcessInformation C linkage error

### ISSUE THREAD

**Issue by grrrwaaa** [sadmb/ofxKinectNui#22]
Just pulled a fresh copy of this and added to OF 0.8 VS release, but building the example project (in VS2012 express, debug, 32) fails with:

Error   7   error C2733: 'GetProcessInformation' : second C linkage of overloaded function not allowed  c:\users\grrrwaaa\documents\of_v0.8.0_vs_release\libs\quicktime\include\processes.h 195 1   example

Probably an upstream OF error -- Why is a QuickTime header being included?

**Comment by sadmb** [comment]
@grrrwaaa 
Thanks for your post.
Finally I worked on solving this. :)
Check the latest version.

FYI, this issue happened because there's the same function in WinBase.h if you define _WIN32_WINNT higher than 0x0602 (which means windows8).
OF avoid this issue by defining _WIN32_WINNT as 0x0500 (which means windows 2000) in ofConstants.h.
So normally this doesn't happen because you include ofMain.h before addons in ofApp.h on most of the projects.
But I had included it after ofxKinectNui.h for avoiding another linkage error when there wasn't this issue.

If you feel not happy to leave _WIN32_WINNT as 0x0500 for some reason like you use another library which doesn't work on 0x0500, then you have to hack Processes.h as below.

```
#if (_WIN32_WINNT < 0x0602)
EXTERN_API( OSErr )
GetProcessInformation           (const ProcessSerialNumber * PSN,
                                 ProcessInfoRec *       info)                               THREEWORDINLINE(0x3F3C, 0x003A, 0xA88F);
#endif
```

Thank you!

**Comment by juansobral** [comment]
Im having the same problem! But couldn't resolve it! Tryed the hack and i'm stille getting the same error

Thank you!

**Comment by caoshun001** [comment]
Im having the same problem too! cant resolve after hack it. And i am using the latest version of ofxKinectNui

**Comment by sadmb** [comment]
@ElGranPelado @caoshun001 
Sorry guys. I found it's not completed yet but have fixed.
Please pull the latest version. ;)

**Comment by juansobral** [comment]
@sadmb Thanks man! Never give thanks for this!
