### ISSUE TITLE
MSR_NuiApi.h

### ISSUE THREAD

**Issue by FdeFabricio** [sadmb/ofxKinectNui#8]
'MSR_NuiApi.h': No such file or directory

This file doens't exist on my computer. Is this really for SDK 1.0?

**Comment by sadmb** [comment]
Hello FdeFabricio,
Thx for post. : )

well, it certainly is a file of SDK beta.
I'm afraid you might download  https://github.com/downloads/sadmb/ofxKinectNui/ofxKinectNui_v002.zip which is the old version uses SDK beta2.
If you want to DL in zip file, Please DL from the top page.
https://github.com/sadmb/ofxKinectNui/zipball/master

I think I've use NuiApi.h instead of MSR_NuiApi.h on all the projects, but if you find some bugs, please tell me which project you tried to compile and where the error is.

Thx so much.

sadam

**Comment by FdeFabricio** [comment]
I did download this version 002.

Actually you didn't change all the "MSR_NuiApi.h" to "NuiApi.h". 
And in the project properties, I had to change in (C/C++)-->(General)-->(Additional Include Directories)   $(KINECTSDK_DIR)\inc for $(KINECTSDK10_DIR)\inc

now I'm getting this errors:

error C2065: 'INuiInstance' : undeclared identifier
error C3861: 'NuiTransformSkeletonToDepthImageF': identifier not found

**Comment by sadmb** [comment]
Hi FdeFabricio,

Sorry, You must download version 003 instead of version 002.
It's available here.
https://github.com/sadmb/ofxKinectNui/zipball/master

Thx for your report.

sadam

**Comment by FdeFabricio** [comment]
Well, I had to add some files on the project... It's working perfectly now, though. Thanks a lot!  =D
